language: ruby
rvm:
- 2.6.3
cache:
  bundler: true
  directories:
  - app/assets/node_modules
  yarn: true
env:
  global:
  - CC_TEST_REPORTER_ID=21bb68f10a2e76bf0f5900574f30703e9237639a08da7f1db2560a8f6dc721b1
services:
- postgresql
before_install:
- gem update —system
- gem install bundler
install:
- bundle install --jobs 3 --retry 3
- nvm install 12
- node -v
- npm i -g yarn
- yarn
before_script:
- bundle exec rails db:create
- bundle exec rails db:migrate
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
script:
- bundle exec rspec
after_script:
- "./cc-test-reporter after-build -t simplecov --exit-code $TRAVIS_TEST_RESULT"
dd:
  secure: Hx//VDlej9/t71R04vPToD2oxw3zqMJT0f0C0D1dUybzxJxrJn2zbx7gk1XpJx5qQPhjdH+kfraYQCCoj6M/TtxjTGBovjodZfcxx1wPOu+1qHYs3ls+AEHRabYrhRFe1hdAbRrt/9B0WnE2cU9HsWWUOoNXktNxdAoG9ZwnHI8tOScobC+mmp36STVI9DnxyZ4cn0c+QF1CaGZYssdScTfAadhYzdAecLz7LlMTADE3SpFDtB+pRYLfed391ANs2Pr5GX7Ms1OS3QLCEU+xOy8z15rhZCk5YXuaMA8deaV9go5UFxqK7nhHK0N0WS7D/Ixw4m5ZpMsFq3nJB5Q7XQp4+5msbStA5xxC/ahjpdlrlivPA5Qe6zMGnOvCfJA9+ynDPG5YSPjkDRrtYpyQ/o01RstpByeOL6RCF74z1EQiZnp2NXwdcc2A0C8J4mizs/ihzcAY5RoyysqtUEcOojWfoiwve33WxydeirvOdlkMfIv4vUWKiOWK2xF9JvCc+S3ctKjG0Kb2fIbvhWpfXD+xPRAsUurGS+aJ9D4LpkZ+PmJGdxQdTTjswj7PBl6QG7XfcwCSzh+I114czBRLZQE98cVtrayK2mtmQgBGcAFthNSn2PzFUg+vn7iz8WAFiWrJ6Ogc+I3YqSd25Xqj/gdLGlUNPxogCDFirR/dPoY=
